<?php
    function arforms_font_awesome_font_array(){
    	
            $font_awesome_icon = array(
                "arfa-address-book" => array( "style" => "fas", "code" => "fa-address-book" ),
                 "arfa-address-book-o" => array( "style" => "far", "code" => "fa-address-book" ),
                 "arfa-address-card" => array( "style" => "fas", "code" => "fa-address-card" ),
                 "arfa-address-card-o" => array( "style" => "far", "code" => "fa-address-card" ),
                 "arfa-bandcamp" => array( "style" => "fab", "code" => "fa-bandcamp" ),
                 "arfa-bath" => array( "style" => "fas", "code" => "fa-bath" ),
                 "arfa-envelope-open" => array( "style" => "fas", "code" => "fa-envelope-open" ),
                 "arfa-envelope-open-o" => array( "style" => "far", "code" => "fa-envelope-open" ),
                 "arfa-etsy" => array( "style" => "fab", "code" => "fa-etsy" ),
                 "arfa-free-code-camp" => array( "style" => "fab", "code" => "fa-free-code-camp" ),
                 "arfa-grav" => array( "style" => "fab", "code" => "fa-grav" ),
                 "arfa-handshake-o" => array( "style" => "far", "code" => "fa-handshake" ),
                 "arfa-id-badge" => array( "style" => "fas", "code" => "fa-id-badge" ),
                 "arfa-id-card" => array( "style" => "fas", "code" => "fa-id-card" ),
                 "arfa-id-card-o" => array( "style" => "far", "code" => "fa-id-card" ),
                 "arfa-imdb" => array( "style" => "fab", "code" => "fa-imdb" ),
                 "arfa-linode" => array( "style" => "fab", "code" => "fa-linode" ),
                 "arfa-meetup" => array( "style" => "fab", "code" => "fa-meetup" ),
                 "arfa-microchip" => array( "style" => "fas", "code" => "fa-microchip" ),
                 "arfa-podcast" => array( "style" => "fas", "code" => "fa-podcast" ),
                 "arfa-quora" => array( "style" => "fab", "code" => "fa-quora" ),
                 "arfa-ravelry" => array( "style" => "fab", "code" => "fa-ravelry" ),
                 "arfa-shower" => array( "style" => "fas", "code" => "fa-shower" ),
                 "arfa-snowflake-o" => array( "style" => "far", "code" => "fa-snowflake" ),
                 "arfa-superpowers" => array( "style" => "fab", "code" => "fa-superpowers" ),
                 "arfa-telegram" => array( "style" => "fab", "code" => "fa-telegram" ),
                 "arfa-thermometer-empty" => array( "style" => "fas", "code" => "fa-thermometer-empty" ),
                 "arfa-thermometer-full" => array( "style" => "fas", "code" => "fa-thermometer-full" ),
                 "arfa-thermometer-half" => array( "style" => "fas", "code" => "fa-thermometer-half" ),
                 "arfa-thermometer-quarter" => array( "style" => "fas", "code" => "fa-thermometer-quarter" ),
                 "arfa-thermometer-three-quarters" => array( "style" => "fas", "code" => "fa-thermometer-three-quarters" ),
                 "arfa-user-circle" => array( "style" => "fas", "code" => "fa-user-circle" ),
                 "arfa-user-circle-o" => array( "style" => "far", "code" => "fa-user-circle" ),
                 "arfa-user-o" => array( "style" => "far", "code" => "fa-user" ),
                 "arfa-window-close" => array( "style" => "fas", "code" => "fa-window-close" ),
                 "arfa-window-close-o" => array( "style" => "far", "code" => "fa-window-close" ),
                 "arfa-window-maximize" => array( "style" => "far", "code" => "fa-window-maximize" ),
                 "arfa-window-minimize" => array( "style" => "fas", "code" => "fa-window-minimize" ),
                 "arfa-window-restore" => array( "style" => "far", "code" => "fa-window-restore" ),
                 "arfa-wpexplorer" => array( "style" => "fab", "code" => "fa-wpexplorer" ),
                 "arfa-adjust" => array( "style" => "fas", "code" => "fa-adjust" ),
                 "arfa-american-sign-language-interpreting" => array( "style" => "fas", "code" => "fa-american-sign-language-interpreting" ),
                 "arfa-anchor" => array( "style" => "fas", "code" => "fa-anchor" ),
                 "arfa-archive" => array( "style" => "fas", "code" => "fa-archive" ),
                 "arfa-area-chart" => array( "style" => "fas", "code" => "fa-chart-area" ),
                 "arfa-arrows" => array( "style" => "fas", "code" => "fa-arrows-alt" ),
                 "arfa-arrows-h" => array( "style" => "fas", "code" => "fa-arrows-alt-h" ),
                 "arfa-arrows-v" => array( "style" => "fas", "code" => "fa-arrows-alt-v" ),
                 "arfa-assistive-listening-systems" => array( "style" => "fas", "code" => "fa-assistive-listening-systems" ),
                 "arfa-asterisk" => array( "style" => "fas", "code" => "fa-asterisk" ),
                 "arfa-at" => array( "style" => "fas", "code" => "fa-at" ),
                 "arfa-audio-description" => array( "style" => "fas", "code" => "fa-audio-description" ),
                 "arfa-balance-scale" => array( "style" => "fas", "code" => "fa-balance-scale" ),
                 "arfa-ban" => array( "style" => "fas", "code" => "fa-ban" ),
                 "arfa-bar-chart" => array( "style" => "fas", "code" => "fa-chart-bar" ),
                 "arfa-barcode" => array( "style" => "fas", "code" => "fa-barcode" ),
                 "arfa-bars" => array( "style" => "fas", "code" => "fa-bars" ),
                 "arfa-battery-empty" => array( "style" => "fas", "code" => "fa-battery-empty" ),
                 "arfa-battery-full" => array( "style" => "fas", "code" => "fa-battery-full" ),
                 "arfa-battery-half" => array( "style" => "fas", "code" => "fa-battery-half" ),
                 "arfa-battery-quarter" => array( "style" => "fas", "code" => "fa-battery-quarter" ),
                 "arfa-battery-three-quarters" => array( "style" => "fas", "code" => "fa-battery-three-quarters" ),
                 "arfa-bed" => array( "style" => "fas", "code" => "fa-bed" ),
                 "arfa-beer" => array( "style" => "fas", "code" => "fa-beer" ),
                 "arfa-bell" => array( "style" => "fas", "code" => "fa-bell" ),
                 "arfa-bell-o" => array( "style" => "far", "code" => "fa-bell" ),
                 "arfa-bell-slash" => array( "style" => "fas", "code" => "fa-bell-slash" ),
                 "arfa-bell-slash-o" => array( "style" => "far", "code" => "fa-bell-slash" ),
                 "arfa-bicycle" => array( "style" => "fas", "code" => "fa-bicycle" ),
                 "arfa-binoculars" => array( "style" => "fas", "code" => "fa-binoculars" ),
                 "arfa-birthday-cake" => array( "style" => "fas", "code" => "fa-birthday-cake" ),
                 "arfa-blind" => array( "style" => "fas", "code" => "fa-blind" ),
                 "arfa-bluetooth" => array( "style" => "fab", "code" => "fa-bluetooth" ),
                 "arfa-bluetooth-b" => array( "style" => "fab", "code" => "fa-bluetooth-b" ),
                 "arfa-bolt" => array( "style" => "fas", "code" => "fa-bolt" ),
                 "arfa-bomb" => array( "style" => "fas", "code" => "fa-bomb" ),
                 "arfa-book" => array( "style" => "fas", "code" => "fa-book" ),
                 "arfa-bookmark" => array( "style" => "fas", "code" => "fa-bookmark" ),
                 "arfa-bookmark-o" => array( "style" => "far", "code" => "fa-bookmark" ),
                 "arfa-braille" => array( "style" => "fas", "code" => "fa-braille" ),
                 "arfa-briefcase" => array( "style" => "fas", "code" => "fa-briefcase" ),
                 "arfa-bug" => array( "style" => "fas", "code" => "fa-bug" ),
                 "arfa-building" => array( "style" => "fas", "code" => "fa-building" ),
                 "arfa-building-o" => array( "style" => "far", "code" => "fa-building" ),
                 "arfa-bullhorn" => array( "style" => "fas", "code" => "fa-bullhorn" ),
                 "arfa-bullseye" => array( "style" => "fas", "code" => "fa-bullseye" ),
                 "arfa-bus" => array( "style" => "fas", "code" => "fa-bus" ),
                 "arfa-calculator" => array( "style" => "fas", "code" => "fa-calculator" ),
                 "arfa-calendar" => array( "style" => "fas", "code" => "fa-calendar" ),
                 "arfa-calendar-check-o" => array( "style" => "far", "code" => "fa-calendar-check" ),
                 "arfa-calendar-minus-o" => array( "style" => "far", "code" => "fa-calendar-minus" ),
                 "arfa-calendar-o" => array( "style" => "far", "code" => "fa-calendar" ),
                 "arfa-calendar-plus-o" => array( "style" => "far", "code" => "fa-calendar-plus" ),
                 "arfa-calendar-times-o" => array( "style" => "far", "code" => "fa-calendar-times" ),
                 "arfa-camera" => array( "style" => "fas", "code" => "fa-camera" ),
                 "arfa-camera-retro" => array( "style" => "fas", "code" => "fa-camera-retro" ),
                 "arfa-car" => array( "style" => "fas", "code" => "fa-car" ),
                 "arfa-caret-square-o-down" => array( "style" => "far", "code" => "fa-caret-square-down" ),
                 "arfa-caret-square-o-left" => array( "style" => "far", "code" => "fa-caret-square-left" ),
                 "arfa-caret-square-o-right" => array( "style" => "far", "code" => "fa-caret-square-right" ),
                 "arfa-caret-square-o-up" => array( "style" => "far", "code" => "fa-caret-square-up" ),
                 "arfa-cart-arrow-down" => array( "style" => "fas", "code" => "fa-cart-arrow-down" ),
                 "arfa-cart-plus" => array( "style" => "fas", "code" => "fa-cart-plus" ),
                 "arfa-cc" => array( "style" => "far", "code" => "fa-closed-captioning" ),
                 "arfa-certificate" => array( "style" => "fas", "code" => "fa-certificate" ),
                 "arfa-check" => array( "style" => "fas", "code" => "fa-check" ),
                 "arfa-check-circle" => array( "style" => "fas", "code" => "fa-check-circle" ),
                 "arfa-check-circle-o" => array( "style" => "far", "code" => "fa-check-circle" ),
                 "arfa-check-square" => array( "style" => "fas", "code" => "fa-check-square" ),
                 "arfa-check-square-o" => array( "style" => "far", "code" => "fa-check-square" ),
                 "arfa-child" => array( "style" => "fas", "code" => "fa-child" ),
                 "arfa-circle" => array( "style" => "fas", "code" => "fa-circle" ),
                 "arfa-circle-o" => array( "style" => "far", "code" => "fa-circle" ),
                 "arfa-circle-thin" => array( "style" => "fas", "code" => "fa-circle" ),
                 "arfa-circle-o-notch" => array( "style" => "fas", "code" => "fa-circle-notch" ),
                 "arfa-clock-o" => array( "style" => "far", "code" => "fa-clock" ),
                 "arfa-clone" => array( "style" => "fas", "code" => "fa-clone" ),
                 "arfa-cloud" => array( "style" => "fas", "code" => "fa-cloud" ),
                 "arfa-cloud-download" => array( "style" => "fas", "code" => "fa-cloud-download-alt" ),
                 "arfa-cloud-upload" => array( "style" => "fas", "code" => "fa-cloud-upload-alt" ),
                 "arfa-code" => array( "style" => "fas", "code" => "fa-code" ),
                 "arfa-code-fork" => array( "style" => "fas", "code" => "fa-code-branch" ),
                 "arfa-coffee" => array( "style" => "fas", "code" => "fa-coffee" ),
                 "arfa-cog" => array( "style" => "fas", "code" => "fa-cog" ),
                 "arfa-cogs" => array( "style" => "fas", "code" => "fa-cogs" ),
                 "arfa-comment" => array( "style" => "fas", "code" => "fa-comment" ),
                 "arfa-comment-o" => array( "style" => "far", "code" => "fa-comment" ),
                 "arfa-commenting" => array( "style" => "fas", "code" => "fa-comment-alt" ),
                 "arfa-commenting-o" => array( "style" => "far", "code" => "fa-comment-alt" ),
                 "arfa-comments" => array( "style" => "fas", "code" => "fa-comments" ),
                 "arfa-comments-o" => array( "style" => "far", "code" => "fa-comments" ),
                 "arfa-compass" => array( "style" => "far", "code" => "fa-compass" ),
                 "arfa-copyright" => array( "style" => "far", "code" => "fa-copyright" ),
                 "arfa-creative-commons" => array( "style" => "fab", "code" => "fa-creative-commons" ),
                 "arfa-credit-card" => array( "style" => "far", "code" => "fa-credit-card" ),
                 "arfa-credit-card-alt" => array( "style" => "fas", "code" => "fa-credit-card" ),
                 "arfa-crop" => array( "style" => "fas", "code" => "fa-crop" ),
                 "arfa-crosshairs" => array( "style" => "fas", "code" => "fa-crosshairs" ),
                 "arfa-cube" => array( "style" => "fas", "code" => "fa-cube" ),
                 "arfa-cubes" => array( "style" => "fas", "code" => "fa-cubes" ),
                 "arfa-cutlery" => array( "style" => "fas", "code" => "fa-utensils" ),
                 "arfa-database" => array( "style" => "fas", "code" => "fa-database" ),
                 "arfa-deaf" => array( "style" => "fas", "code" => "fa-deaf" ),
                 "arfa-desktop" => array( "style" => "fas", "code" => "fa-desktop" ),
                 "arfa-diamond" => array( "style" => "far", "code" => "fa-gem" ),
                 "arfa-dot-circle-o" => array( "style" => "far", "code" => "fa-dot-circle" ),
                 "arfa-download" => array( "style" => "fas", "code" => "fa-download" ),
                 "arfa-ellipsis-h" => array( "style" => "fas", "code" => "fa-ellipsis-h" ),
                 "arfa-ellipsis-v" => array( "style" => "fas", "code" => "fa-ellipsis-v" ),
                 "arfa-envelope" => array( "style" => "fas", "code" => "fa-envelope" ),
                 "arfa-envelope-o" => array( "style" => "far", "code" => "fa-envelope" ),
                 "arfa-envelope-square" => array( "style" => "fas", "code" => "fa-envelope-square" ),
                 "arfa-eraser" => array( "style" => "fas", "code" => "fa-eraser" ),
                 "arfa-exchange" => array( "style" => "fas", "code" => "fa-exchange-alt" ),
                 "arfa-exclamation" => array( "style" => "fas", "code" => "fa-exclamation" ),
                 "arfa-exclamation-circle" => array( "style" => "fas", "code" => "fa-exclamation-circle" ),
                 "arfa-exclamation-triangle" => array( "style" => "fas", "code" => "fa-exclamation-triangle" ),
                 "arfa-external-link" => array( "style" => "fas", "code" => "fa-external-link-alt" ),
                 "arfa-external-link-square" => array( "style" => "fas", "code" => "fa-external-link-square-alt" ),
                 "arfa-eye" => array( "style" => "fas", "code" => "fa-eye" ),
                 "arfa-eye-slash" => array( "style" => "far", "code" => "fa-eye-slash" ),
                 "arfa-eyedropper" => array( "style" => "fas", "code" => "fa-eye-dropper" ),
                 "arfa-fax" => array( "style" => "fas", "code" => "fa-fax" ),
                 "arfa-female" => array( "style" => "fas", "code" => "fa-female" ),
                 "arfa-fighter-jet" => array( "style" => "fas", "code" => "fa-fighter-jet" ),
                 "arfa-file-archive-o" => array( "style" => "far", "code" => "fa-file-archive" ),
                 "arfa-file-audio-o" => array( "style" => "far", "code" => "fa-file-audio" ),
                 "arfa-file-code-o" => array( "style" => "far", "code" => "fa-file-code" ),
                 "arfa-file-excel-o" => array( "style" => "far", "code" => "fa-file-excel" ),
                 "arfa-file-image-o" => array( "style" => "far", "code" => "fa-file-image" ),
                 "arfa-file-pdf-o" => array( "style" => "far", "code" => "fa-file-pdf" ),
                 "arfa-file-powerpoint-o" => array( "style" => "far", "code" => "fa-file-powerpoint" ),
                 "arfa-file-video-o" => array( "style" => "far", "code" => "fa-file-video" ),
                 "arfa-file-word-o" => array( "style" => "far", "code" => "fa-file-word" ),
                 "arfa-film" => array( "style" => "fas", "code" => "fa-film" ),
                 "arfa-filter" => array( "style" => "fas", "code" => "fa-filter" ),
                 "arfa-fire" => array( "style" => "fas", "code" => "fa-fire" ),
                 "arfa-fire-extinguisher" => array( "style" => "fas", "code" => "fa-fire-extinguisher" ),
                 "arfa-flag" => array( "style" => "fas", "code" => "fa-flag" ),
                 "arfa-flag-checkered" => array( "style" => "fas", "code" => "fa-flag-checkered" ),
                 "arfa-flag-o" => array( "style" => "far", "code" => "fa-flag" ),
                 "arfa-flask" => array( "style" => "fas", "code" => "fa-flask" ),
                 "arfa-folder" => array( "style" => "fas", "code" => "fa-folder" ),
                 "arfa-folder-o" => array( "style" => "far", "code" => "fa-folder" ),
                 "arfa-folder-open" => array( "style" => "fas", "code" => "fa-folder-open" ),
                 "arfa-folder-open-o" => array( "style" => "far", "code" => "fa-folder-open" ),
                 "arfa-frown-o" => array( "style" => "far", "code" => "fa-frown" ),
                 "arfa-futbol-o" => array( "style" => "fas", "code" => "fa-futbol" ),
                 "arfa-gamepad" => array( "style" => "fas", "code" => "fa-gamepad" ),
                 "arfa-gavel" => array( "style" => "fas", "code" => "fa-gavel" ),
                 "arfa-gift" => array( "style" => "fas", "code" => "fa-gift" ),
                 "arfa-glass" => array( "style" => "fas", "code" => "fa-glass-martini" ),
                 "arfa-globe" => array( "style" => "fas", "code" => "fa-globe" ),
                 "arfa-graduation-cap" => array( "style" => "fas", "code" => "fa-graduation-cap" ),
				 "arfa-hand-lizard-o" => array( "style" => "far", "code" => "fa-hand-lizard" ),
                 "arfa-hand-paper-o" => array( "style" => "far", "code" => "fa-hand-paper" ),
                 "arfa-hand-peace-o" => array( "style" => "far", "code" => "fa-hand-peace" ),
                 "arfa-hand-pointer-o" => array( "style" => "far", "code" => "fa-hand-pointer" ),
                 "arfa-hand-rock-o" => array( "style" => "far", "code" => "fa-hand-rock" ),
                 "arfa-hand-scissors-o" => array( "style" => "far", "code" => "fa-hand-scissors" ),
                 "arfa-hand-spock-o" => array( "style" => "far", "code" => "fa-hand-spock" ),
                 "arfa-hashtag" => array( "style" => "fas", "code" => "fa-hashtag" ),
                 "arfa-hdd-o" => array( "style" => "far", "code" => "fa-hdd" ),
                 "arfa-headphones" => array( "style" => "fas", "code" => "fa-headphones" ),
                 "arfa-heart" => array( "style" => "fas", "code" => "fa-heart" ),
                 "arfa-heart-o" => array( "style" => "far", "code" => "fa-heart" ),
                 "arfa-heartbeat" => array( "style" => "fas", "code" => "fa-heartbeat" ),
                 "arfa-history" => array( "style" => "fas", "code" => "fa-history" ),
                 "arfa-home" => array( "style" => "fas", "code" => "fa-home" ),
                 "arfa-hourglass" => array( "style" => "fas", "code" => "fa-hourglass" ),
                 "arfa-hourglass-end" => array( "style" => "fas", "code" => "fa-hourglass-end" ),
                 "arfa-hourglass-half" => array( "style" => "fas", "code" => "fa-hourglass-half" ),
                 "arfa-hourglass-o" => array( "style" => "far", "code" => "fa-hourglass" ),
                 "arfa-hourglass-start" => array( "style" => "fas", "code" => "fa-hourglass-start" ),
                 "arfa-i-cursor" => array( "style" => "fas", "code" => "fa-i-cursor" ),
                 "arfa-inbox" => array( "style" => "fas", "code" => "fa-inbox" ),
                 "arfa-industry" => array( "style" => "fas", "code" => "fa-industry" ),
                 "arfa-info" => array( "style" => "fas", "code" => "fa-info" ),
                 "arfa-info-circle" => array( "style" => "fas", "code" => "fa-info-circle" ),
                 "arfa-key" => array( "style" => "fas", "code" => "fa-key" ),
                 "arfa-keyboard-o" => array( "style" => "far", "code" => "fa-keyboard" ),
                 "arfa-language" => array( "style" => "fas", "code" => "fa-language" ),
                 "arfa-laptop" => array( "style" => "fas", "code" => "fa-laptop" ),
                 "arfa-leaf" => array( "style" => "fas", "code" => "fa-leaf" ),
                 "arfa-lemon-o" => array( "style" => "far", "code" => "fa-lemon" ),
                 "arfa-level-down" => array( "style" => "fas", "code" => "fa-level-down-alt" ),
                 "arfa-level-up" => array( "style" => "fas", "code" => "fa-level-up-alt" ),
                 "arfa-life-ring" => array( "style" => "far", "code" => "fa-life-ring" ),
                 "arfa-lightbulb-o" => array( "style" => "far", "code" => "fa-lightbulb" ),
                 "arfa-line-chart" => array( "style" => "fas", "code" => "fa-chart-line" ),
                 "arfa-location-arrow" => array( "style" => "fas", "code" => "fa-location-arrow" ),
                 "arfa-lock" => array( "style" => "fas", "code" => "fa-lock" ),
                 "arfa-low-vision" => array( "style" => "fas", "code" => "fa-low-vision" ),
                 "arfa-magic" => array( "style" => "fas", "code" => "fa-magic" ),
                 "arfa-magnet" => array( "style" => "fas", "code" => "fa-magnet" ),
                 "arfa-male" => array( "style" => "fas", "code" => "fa-male" ),
                 "arfa-map" => array( "style" => "fas", "code" => "fa-map" ),
                 "arfa-map-marker" => array( "style" => "fas", "code" => "fa-map-marker" ),
                 "arfa-map-o" => array( "style" => "far", "code" => "fa-map" ),
                 "arfa-map-pin" => array( "style" => "fas", "code" => "fa-map-pin" ),
                 "arfa-map-signs" => array( "style" => "fas", "code" => "fa-map-signs" ),
                 "arfa-meh-o" => array( "style" => "far", "code" => "fa-meh" ),
                 "arfa-microphone" => array( "style" => "fas", "code" => "fa-microphone" ),
                 "arfa-microphone-slash" => array( "style" => "fas", "code" => "fa-microphone-slash" ),
                 "arfa-minus" => array( "style" => "fas", "code" => "fa-minus" ),
                 "arfa-minus-circle" => array( "style" => "fas", "code" => "fa-minus-circle" ),
                 "arfa-minus-square" => array( "style" => "fas", "code" => "fa-minus-square" ),
                 "arfa-minus-square-o" => array( "style" => "far", "code" => "fa-minus-square" ),
                 "arfa-mobile" => array( "style" => "fas", "code" => "fa-mobile" ),
                 "arfa-money" => array( "style" => "far", "code" => "fa-money-bill-alt" ),
                 "arfa-moon-o" => array( "style" => "far", "code" => "fa-moon" ),
                 "arfa-motorcycle" => array( "style" => "fas", "code" => "fa-motorcycle" ),
                 "arfa-mouse-pointer" => array( "style" => "fas", "code" => "fa-mouse-pointer" ),
                 "arfa-music" => array( "style" => "fas", "code" => "fa-music" ),
                 "arfa-newspaper-o" => array( "style" => "far", "code" => "fa-newspaper" ),
                 "arfa-object-group" => array( "style" => "far", "code" => "fa-object-group" ),
                 "arfa-object-ungroup" => array( "style" => "far", "code" => "fa-object-ungroup" ),
                 "arfa-paint-brush" => array( "style" => "fas", "code" => "fa-paint-brush" ),
                 "arfa-paper-plane" => array( "style" => "fas", "code" => "fa-paper-plane" ),
                 "arfa-paper-plane-o" => array( "style" => "far", "code" => "fa-paper-plane" ),
                 "arfa-paw" => array( "style" => "fas", "code" => "fa-paw" ),
                 "arfa-pencil" => array( "style" => "fas", "code" => "fa-pencil-alt" ),
                 "arfa-pencil-square" => array( "style" => "fas", "code" => "fa-pen-square" ),
                 "arfa-pencil-square-o" => array( "style" => "far", "code" => "fa-edit" ),
                 "arfa-percent" => array( "style" => "fas", "code" => "fa-percent" ),
                 "arfa-phone" => array( "style" => "fas", "code" => "fa-phone" ),
                 "arfa-phone-square" => array( "style" => "fas", "code" => "fa-phone-square" ),
                 "arfa-picture-o" => array( "style" => "far", "code" => "fa-image" ),
                 "arfa-pie-chart" => array( "style" => "fas", "code" => "fa-chart-pie" ),
                 "arfa-plane" => array( "style" => "fas", "code" => "fa-plane" ),
                 "arfa-plug" => array( "style" => "fas", "code" => "fa-plug" ),
                 "arfa-plus" => array( "style" => "fas", "code" => "fa-plus" ),
                 "arfa-plus-circle" => array( "style" => "fas", "code" => "fa-plus-circle" ),
                 "arfa-plus-square" => array( "style" => "fas", "code" => "fa-plus-square" ),
                 "arfa-plus-square-o" => array( "style" => "far", "code" => "fa-plus-square" ),
                 "arfa-power-off" => array( "style" => "fas", "code" => "fa-power-off" ),
                 "arfa-print" => array( "style" => "fas", "code" => "fa-print" ),
                 "arfa-puzzle-piece" => array( "style" => "fas", "code" => "fa-puzzle-piece" ),
                 "arfa-qrcode" => array( "style" => "fas", "code" => "fa-qrcode" ),
                 "arfa-question" => array( "style" => "fas", "code" => "fa-question" ),
                 "arfa-question-circle" => array( "style" => "fas", "code" => "fa-question-circle" ),
                 "arfa-question-circle-o" => array( "style" => "far", "code" => "fa-question-circle" ),
                 "arfa-quote-left" => array( "style" => "fas", "code" => "fa-quote-left" ),
                 "arfa-quote-right" => array( "style" => "fas", "code" => "fa-quote-right" ),
                 "arfa-random" => array( "style" => "fas", "code" => "fa-random" ),
                 "arfa-recycle" => array( "style" => "fas", "code" => "fa-recycle" ),
                 "arfa-refresh" => array( "style" => "fas", "code" => "fa-sync-alt" ),
                 "arfa-registered" => array( "style" => "fas", "code" => "fa-registered" ),
                 "arfa-reply" => array( "style" => "fas", "code" => "fa-reply" ),
                 "arfa-reply-all" => array( "style" => "fas", "code" => "fa-reply-all" ),
                 "arfa-retweet" => array( "style" => "fas", "code" => "fa-retweet" ),
                 "arfa-road" => array( "style" => "fas", "code" => "fa-road" ),
                 "arfa-rocket" => array( "style" => "fas", "code" => "fa-rocket" ),
                 "arfa-rss" => array( "style" => "fas", "code" => "fa-rss" ),
                 "arfa-rss-square" => array( "style" => "fas", "code" => "fa-rss-square" ),
                 "arfa-search" => array( "style" => "fas", "code" => "fa-search" ),
                 "arfa-search-minus" => array( "style" => "fas", "code" => "fa-search-minus" ),
                 "arfa-search-plus" => array( "style" => "fas", "code" => "fa-search-plus" ),
                 "arfa-server" => array( "style" => "fas", "code" => "fa-server" ),
                 "arfa-share" => array( "style" => "fas", "code" => "fa-share" ),
                 "arfa-share-alt" => array( "style" => "fas", "code" => "fa-share-alt" ),
                 "arfa-share-alt-square" => array( "style" => "fas", "code" => "fa-share-alt-square" ),
                 "arfa-share-square" => array( "style" => "fas", "code" => "fa-share-square" ),
                 "arfa-share-square-o" => array( "style" => "far", "code" => "fa-share-square" ),
                 "arfa-shield" => array( "style" => "fas", "code" => "fa-shield-alt" ),
                 "arfa-ship" => array( "style" => "fas", "code" => "fa-ship" ),
                 "arfa-shopping-bag" => array( "style" => "fas", "code" => "fa-shopping-bag" ),
                 "arfa-shopping-basket" => array( "style" => "fas", "code" => "fa-shopping-basket" ),
                 "arfa-shopping-cart" => array( "style" => "fas", "code" => "fa-shopping-cart" ),
                 "arfa-sign-in" => array( "style" => "fas", "code" => "fa-sign-in-alt" ),
                 "arfa-sign-language" => array( "style" => "fas", "code" => "fa-sign-language" ),
                 "arfa-sign-out" => array( "style" => "fas", "code" => "fa-sign-out-alt" ),
                 "arfa-signal" => array( "style" => "fas", "code" => "fa-signal" ),
                 "arfa-sitemap" => array( "style" => "fas", "code" => "fa-sitemap" ),
                 "arfa-sliders" => array( "style" => "fas", "code" => "fa-sliders-h" ),
                 "arfa-smile-o" => array( "style" => "far", "code" => "fa-smile" ),
                 "arfa-sort" => array( "style" => "fas", "code" => "fa-sort" ),
                 "arfa-sort-alpha-asc" => array( "style" => "fas", "code" => "fa-sort-alpha-up" ),
                 "arfa-sort-alpha-desc" => array( "style" => "fas", "code" => "fa-sort-alpha-down" ),
                 "arfa-sort-amount-asc" => array( "style" => "fas", "code" => "fa-sort-amount-up" ),
                 "arfa-sort-amount-desc" => array( "style" => "fas", "code" => "fa-sort-amount-down" ),
                 "arfa-sort-asc" => array( "style" => "fas", "code" => "fa-sort-up" ),
                 "arfa-sort-desc" => array( "style" => "fas", "code" => "fa-sort-down" ),
                 "arfa-sort-numeric-asc" => array( "style" => "fas", "code" => "fa-sort-numeric-up" ),
                 "arfa-sort-numeric-desc" => array( "style" => "fas", "code" => "fa-sort-numeric-down" ),
                 "arfa-space-shuttle" => array( "style" => "fas", "code" => "fa-space-shuttle" ),
                 "arfa-spinner" => array( "style" => "fas", "code" => "fa-spinner" ),
                 "arfa-spoon" => array( "style" => "fas", "code" => "fa-utensil-spoon" ),
                 "arfa-square" => array( "style" => "fas", "code" => "fa-square" ),
                 "arfa-square-o" => array( "style" => "far", "code" => "fa-square" ),
                 "arfa-star" => array( "style" => "fas", "code" => "fa-star" ),
                 "arfa-star-half" => array( "style" => "fas", "code" => "fa-star-half" ),
                 "arfa-star-half-o" => array( "style" => "far", "code" => "fa-star-half" ),
                 "arfa-star-o" => array( "style" => "far", "code" => "fa-star" ),
                 "arfa-sticky-note" => array( "style" => "fas", "code" => "fa-sticky-note" ),
                 "arfa-sticky-note-o" => array( "style" => "far", "code" => "fa-sticky-note" ),
                 "arfa-street-view" => array( "style" => "fas", "code" => "fa-street-view" ),
                 "arfa-suitcase" => array( "style" => "fas", "code" => "fa-suitcase" ),
                 "arfa-sun-o" => array( "style" => "far", "code" => "fa-sun" ),
                 "arfa-tablet" => array( "style" => "fas", "code" => "fa-tablet" ),
                 "arfa-tablets" => array( "style" => "fas", "code" => "fa-tablets" ),
                 "arfa-tablet-alt" => array( "style" => "fas", "code" => "fa-tablet-alt"),
                 "arfa-tachometer" => array( "style" => "fas", "code" => "fa-tachometer-alt" ),
                 "arfa-tag" => array( "style" => "fas", "code" => "fa-tag" ),
                 "arfa-tags" => array( "style" => "fas", "code" => "fa-tags" ),
                 "arfa-tasks" => array( "style" => "fas", "code" => "fa-tasks" ),
                 "arfa-taxi" => array( "style" => "fas", "code" => "fa-taxi" ),
                 "arfa-television" => array( "style" => "fas", "code" => "fa-tv" ),
                 "arfa-terminal" => array( "style" => "fas", "code" => "fa-terminal" ),
                 "arfa-thumb-tack" => array( "style" => "fas", "code" => "fa-thumbtack" ),
                 "arfa-thumbs-down" => array( "style" => "fas", "code" => "fa-thumbs-down" ),
                 "arfa-thumbs-o-down" => array( "style" => "far", "code" => "fa-thumbs-down" ),
                 "arfa-thumbs-o-up" => array( "style" => "far", "code" => "fa-thumbs-up" ),
                 "arfa-thumbs-up" => array( "style" => "fas", "code" => "fa-thumbs-up" ),
                 "arfa-ticket" => array( "style" => "fas", "code" => "fa-ticket-alt" ),
                 "arfa-times" => array( "style" => "fas", "code" => "fa-times" ),
                 "arfa-times-circle" => array( "style" => "fas", "code" => "fa-times-circle" ),
                 "arfa-times-circle-o" => array( "style" => "far", "code" => "fa-times-circle" ),
                 "arfa-tint" => array( "style" => "fas", "code" => "fa-tint" ),
                 "arfa-toggle-off" => array( "style" => "fas", "code" => "fa-toggle-off" ),
                 "arfa-toggle-on" => array( "style" => "fas", "code" => "fa-toggle-on" ),
                 "arfa-trademark" => array( "style" => "fas", "code" => "fa-trademark" ),
                 "arfa-trash" => array( "style" => "fas", "code" => "fa-trash-alt" ),
                 "arfa-trash-o" => array( "style" => "far", "code" => "fa-trash-alt" ),
                 "arfa-tree" => array( "style" => "fas", "code" => "fa-tree" ),
                 "arfa-trophy" => array( "style" => "fas", "code" => "fa-trophy" ),
                 "arfa-truck" => array( "style" => "fas", "code" => "fa-truck" ),
                 "arfa-tty" => array( "style" => "fas", "code" => "fa-tty" ),
                 "arfa-umbrella" => array( "style" => "fas", "code" => "fa-umbrella" ),
                 "arfa-universal-access" => array( "style" => "fas", "code" => "fa-universal-access" ),
                 "arfa-university" => array( "style" => "fas", "code" => "fa-university" ),
                 "arfa-unlock" => array( "style" => "fas", "code" => "fa-unlock" ),
                 "arfa-unlock-alt" => array( "style" => "fas", "code" => "fa-unlock-alt" ),
                 "arfa-upload" => array( "style" => "fas", "code" => "fa-upload" ),
                 "arfa-user" => array( "style" => "fas", "code" => "fa-user" ),
                 "arfa-user-plus" => array( "style" => "fas", "code" => "fa-user-plus" ),
                 "arfa-user-secret" => array( "style" => "fas", "code" => "fa-user-secret" ),
                 "arfa-user-times" => array( "style" => "fas", "code" => "fa-user-times" ),
                 "arfa-users" => array( "style" => "fas", "code" => "fa-users" ),
                 "arfa-video-camera" => array( "style" => "fas", "code" => "fa-video" ),
                 "arfa-volume-control-phone" => array( "style" => "fas", "code" => "fa-phone-volume" ),
                 "arfa-volume-down" => array( "style" => "fas", "code" => "fa-volume-down" ),
                 "arfa-volume-off" => array( "style" => "fas", "code" => "fa-volume-off" ),
                 "arfa-volume-up" => array( "style" => "fas", "code" => "fa-volume-up" ),
                 "arfa-wheelchair" => array( "style" => "fas", "code" => "fa-wheelchair" ),
                 "arfa-wheelchair-alt" => array( "style" => "fab", "code" => "fa-accessible-icon" ),
                 "arfa-wifi" => array( "style" => "fas", "code" => "fa-wifi" ),
                 "arfa-wrench" => array( "style" => "fas", "code" => "fa-wrench" ),
                 "arfa-hand-o-down" => array( "style" => "far", "code" => "fa-hand-point-down" ),
                 "arfa-hand-o-left" => array( "style" => "far", "code" => "fa-hand-point-left" ),
                 "arfa-hand-o-right" => array( "style" => "far", "code" => "fa-hand-point-right" ),
                 "arfa-hand-o-up" => array( "style" => "far", "code" => "fa-hand-point-up" ),
                 "arfa-ambulance" => array( "style" => "fas", "code" => "fa-ambulance" ),
                 "arfa-subway" => array( "style" => "fas", "code" => "fa-subway" ),
                 "arfa-train" => array( "style" => "fas", "code" => "fa-train" ),
                 "arfa-genderless" => array( "style" => "fas", "code" => "fa-genderless" ),
                 "arfa-mars" => array( "style" => "fas", "code" => "fa-mars" ),
                 "arfa-mars-double" => array( "style" => "fas", "code" => "fa-mars-double" ),
                 "arfa-mars-stroke" => array( "style" => "fas", "code" => "fa-mars-stroke" ),
                 "arfa-mars-stroke-h" => array( "style" => "fas", "code" => "fa-mars-stroke-h" ),
                 "arfa-mars-stroke-v" => array( "style" => "fas", "code" => "fa-mars-stroke-v" ),
                 "arfa-mercury" => array( "style" => "fas", "code" => "fa-mercury" ),
                 "arfa-neuter" => array( "style" => "fas", "code" => "fa-neuter" ),
                 "arfa-transgender" => array( "style" => "fas", "code" => "fa-transgender" ),
                 "arfa-transgender-alt" => array( "style" => "fas", "code" => "fa-transgender-alt" ),
                 "arfa-venus" => array( "style" => "fas", "code" => "fa-venus" ),
                 "arfa-venus-double" => array( "style" => "fas", "code" => "fa-venus-double" ),
                 "arfa-venus-mars" => array( "style" => "fas", "code" => "fa-venus-mars" ),
                 "arfa-file" => array( "style" => "fas", "code" => "fa-file" ),
                 "arfa-file-o" => array( "style" => "far", "code" => "fa-file" ),
                 "arfa-file-text" => array( "style" => "fas", "code" => "fa-file-alt" ),
                 "arfa-file-text-o" => array( "style" => "far", "code" => "fa-file-alt" ),
                 "arfa-cc-amex" => array( "style" => "fab", "code" => "fa-cc-amex" ),
                 "arfa-cc-diners-club" => array( "style" => "fab", "code" => "fa-cc-diners-club" ),
                 "arfa-cc-discover" => array( "style" => "fab", "code" => "fa-cc-discover" ),
                 "arfa-cc-jcb" => array( "style" => "fab", "code" => "fa-cc-jcb" ),
                 "arfa-cc-mastercard" => array( "style" => "fab", "code" => "fa-cc-mastercard" ),
                 "arfa-cc-paypal" => array( "style" => "fab", "code" => "fa-cc-paypal" ),
                 "arfa-cc-stripe" => array( "style" => "fab", "code" => "fa-cc-stripe" ),
                 "arfa-cc-visa" => array( "style" => "fab", "code" => "fa-cc-visa" ),
                 "arfa-google-wallet" => array( "style" => "fab", "code" => "fa-google-wallet" ),
                 "arfa-paypal" => array( "style" => "fab", "code" => "fa-paypal" ),
                 "arfa-btc" => array( "style" => "fab", "code" => "fa-btc" ),
                 "arfa-eur" => array( "style" => "fas", "code" => "fa-euro-sign" ),
                 "arfa-gbp" => array( "style" => "fas", "code" => "fa-pound-sign" ),
                 "arfa-gg" => array( "style" => "fab", "code" => "fa-gg" ),
                 "arfa-gg-circle" => array( "style" => "fab", "code" => "fa-gg-circle" ),
                 "arfa-ils" => array( "style" => "fas", "code" => "fa-shekel-sign" ),
                 "arfa-inr" => array( "style" => "fas", "code" => "fa-rupee-sign" ),
                 "arfa-jpy" => array( "style" => "fas", "code" => "fa-yen-sign" ),
                 "arfa-krw" => array( "style" => "fas", "code" => "fa-won-sign" ),
                 "arfa-rub" => array( "style" => "fas", "code" => "fa-ruble-sign " ),
                 "arfa-try" => array( "style" => "fas", "code" => "fa-lira-sign" ),
                 "arfa-usd" => array( "style" => "fas", "code" => "fa-dollar-sign" ),
                 "arfa-align-center" => array( "style" => "fas", "code" => "fa-align-center" ),
                 "arfa-align-justify" => array( "style" => "fas", "code" => "fa-align-justify" ),
                 "arfa-align-left" => array( "style" => "fas", "code" => "fa-align-left" ),
                 "arfa-align-right" => array( "style" => "fas", "code" => "fa-align-right" ),
                 "arfa-bold" => array( "style" => "fas", "code" => "fa-bold" ),
                 "arfa-chain-broken" => array( "style" => "fas", "code" => "fa-unlink" ),
                 "arfa-columns" => array( "style" => "fas", "code" => "fa-columns" ),
                 "arfa-floppy-o" => array( "style" => "far", "code" => "fa-save" ),
                 "arfa-files-o" => array( "style" => "far", "code" => "fa-file" ),
                 "arfa-font" => array( "style" => "fas", "code" => "fa-font" ),
                 "arfa-header" => array( "style" => "fas", "code" => "fa-heading" ),
                 "arfa-indent" => array( "style" => "fas", "code" => "fa-indent" ),
                 "arfa-italic" => array( "style" => "fas", "code" => "fa-italic" ),
                 "arfa-link" => array( "style" => "fas", "code" => "fa-link" ),
                 "arfa-list" => array( "style" => "fas", "code" => "fa-list" ),
                 "arfa-list-alt" => array( "style" => "far", "code" => "fa-list-alt" ),
                 "arfa-list-ol" => array( "style" => "fas", "code" => "fa-list-ol" ),
                 "arfa-list-ul" => array( "style" => "fas", "code" => "fa-list-ul" ),
                 "arfa-outdent" => array( "style" => "fas", "code" => "fa-outdent" ),
                 "arfa-paperclip" => array( "style" => "fas", "code" => "fa-paperclip" ),
                 "arfa-paragraph" => array( "style" => "fas", "code" => "fa-paragraph" ),
                 "arfa-repeat" => array( "style" => "fas", "code" => "fa-redo-alt" ),
                 "arfa-scissors" => array( "style" => "fas", "code" => "fa-cut" ),
                 "arfa-strikethrough" => array( "style" => "fas", "code" => "fa-strikethrough" ),
                 "arfa-subscript" => array( "style" => "fas", "code" => "fa-subscript" ),
                 "arfa-superscript" => array( "style" => "fas", "code" => "fa-superscript" ),
                 "arfa-table" => array( "style" => "fas", "code" => "fa-table" ),
                 "arfa-text-height" => array( "style" => "fas", "code" => "fa-text-height" ),
                 "arfa-text-width" => array( "style" => "fas", "code" => "fa-text-width" ),
                 "arfa-th" => array( "style" => "fas", "code" => "fa-th" ),
                 "arfa-th-large" => array( "style" => "fas", "code" => "fa-th-large" ),
                 "arfa-th-list" => array( "style" => "fas", "code" => "fa-th-list" ),
                 "arfa-underline" => array( "style" => "fas", "code" => "fa-underline" ),
                 "arfa-undo" => array( "style" => "fas", "code" => "fa-undo" ),
                 "arfa-angle-double-down" => array( "style" => "fas", "code" => "fa-angle-double-down" ),
                 "arfa-angle-double-left" => array( "style" => "fas", "code" => "fa-angle-double-left" ),
                 "arfa-angle-double-right" => array( "style" => "fas", "code" => "fa-angle-double-right" ),
                 "arfa-angle-double-up" => array( "style" => "fas", "code" => "fa-angle-double-up" ),
                 "arfa-angle-down" => array( "style" => "fas", "code" => "fa-angle-down" ),
                 "arfa-angle-left" => array( "style" => "fas", "code" => "fa-angle-left" ),
                 "arfa-angle-right" => array( "style" => "fas", "code" => "fa-angle-right" ),
                 "arfa-angle-up" => array( "style" => "fas", "code" => "fa-angle-up" ),
                 "arfa-arrow-circle-down" => array( "style" => "fas", "code" => "fa-arrow-circle-down" ),
                 "arfa-arrow-circle-left" => array( "style" => "fas", "code" => "fa-arrow-circle-left" ),
                 "arfa-arrow-circle-o-down" => array( "style" => "far", "code" => "fa-arrow-alt-circle-down" ),
                 "arfa-arrow-circle-o-left" => array( "style" => "far", "code" => "fa-arrow-alt-circle-left" ),
                 "arfa-arrow-circle-o-right" => array( "style" => "far", "code" => "fa-arrow-alt-circle-right" ),
                 "arfa-arrow-circle-o-up" => array( "style" => "far", "code" => "fa-arrow-alt-circle-up" ),
                 "arfa-arrow-circle-right" => array( "style" => "fas", "code" => "fa-arrow-circle-right" ),
                 "arfa-arrow-circle-up" => array( "style" => "fas", "code" => "fa-arrow-circle-up" ),
                 "arfa-arrow-down" => array( "style" => "fas", "code" => "fa-arrow-down" ),
                 "arfa-arrow-left" => array( "style" => "fas", "code" => "fa-arrow-left" ),
                 "arfa-arrow-right" => array( "style" => "fas", "code" => "fa-arrow-right" ),
                 "arfa-arrow-up" => array( "style" => "fas", "code" => "fa-arrow-up" ),
                 "arfa-arrows-alt" => array( "style" => "fas", "code" => "fa-arrows-alt" ),
                 "arfa-caret-down" => array( "style" => "fas", "code" => "fa-caret-down" ),
                 "arfa-caret-left" => array( "style" => "fas", "code" => "fa-caret-left" ),
                 "arfa-caret-right" => array( "style" => "fas", "code" => "fa-caret-right" ),
                 "arfa-caret-up" => array( "style" => "fas", "code" => "fa-caret-up" ),
                 "arfa-chevron-circle-down" => array( "style" => "fas", "code" => "fa-chevron-circle-down" ),
                 "arfa-chevron-circle-left" => array( "style" => "fas", "code" => "fa-chevron-circle-left" ),
                 "arfa-chevron-circle-right" => array( "style" => "fas", "code" => "fa-chevron-circle-right" ),
                 "arfa-chevron-circle-up" => array( "style" => "fas", "code" => "fa-chevron-circle-up" ),
                 "arfa-chevron-down" => array( "style" => "fas", "code" => "fa-chevron-down" ),
                 "arfa-chevron-left" => array( "style" => "fas", "code" => "fa-chevron-left" ),
                 "arfa-chevron-right" => array( "style" => "fas", "code" => "fa-chevron-right" ),
                 "arfa-chevron-up" => array( "style" => "fas", "code" => "fa-chevron-up" ),
                 "arfa-long-arrow-down" => array( "style" => "fas", "code" => "fa-long-arrow-alt-down" ),
                 "arfa-long-arrow-left" => array( "style" => "fas", "code" => "fa-long-arrow-alt-left" ),
                 "arfa-long-arrow-right" => array( "style" => "fas", "code" => "fa-long-arrow-alt-right" ),
                 "arfa-long-arrow-up" => array( "style" => "fas", "code" => "fa-long-arrow-alt-up" ),
                 "arfa-backward" => array( "style" => "fas", "code" => "fa-backward" ),
                 "arfa-compress" => array( "style" => "fas", "code" => "fa-compress" ),
                 "arfa-eject" => array( "style" => "fas", "code" => "fa-eject" ),
                 "arfa-expand" => array( "style" => "fas", "code" => "fa-expand" ),
                 "arfa-fast-backward" => array( "style" => "fas", "code" => "fa-fast-backward" ),
                 "arfa-fast-forward" => array( "style" => "fas", "code" => "fa-fast-forward" ),
                 "arfa-forward" => array( "style" => "fas", "code" => "fa-forward" ),
                 "arfa-pause" => array( "style" => "fas", "code" => "fa-pause" ),
                 "arfa-pause-circle" => array( "style" => "fas", "code" => "fa-pause-circle" ),
                 "arfa-pause-circle-o" => array( "style" => "far", "code" => "fa-pause-circle" ),
                 "arfa-play" => array( "style" => "fas", "code" => "fa-play" ),
                 "arfa-play-circle" => array( "style" => "fas", "code" => "fa-play-circle" ),
                 "arfa-play-circle-o" => array( "style" => "far", "code" => "fa-play-circle" ),
                 "arfa-step-backward" => array( "style" => "fas", "code" => "fa-step-backward" ),
                 "arfa-step-forward" => array( "style" => "fas", "code" => "fa-step-forward" ),
                 "arfa-stop" => array( "style" => "fas", "code" => "fa-stop" ),
                 "arfa-stop-circle" => array( "style" => "fas", "code" => "fa-stop-circle" ),
                 "arfa-stop-circle-o" => array( "style" => "far", "code" => "fa-stop-circle" ),
                 "arfa-500px" => array( "style" => "fab", "code" => "fa-500px" ),
                 "arfa-adn" => array( "style" => "fab", "code" => "fa-adn" ),
                 "arfa-amazon" => array( "style" => "fab", "code" => "fa-amazon" ),
                 "arfa-android" => array( "style" => "fab", "code" => "fa-android" ),
                 "arfa-angellist" => array( "style" => "fab", "code" => "fa-angellist" ),
                 "arfa-apple" => array( "style" => "fab", "code" => "fa-apple" ),
                 "arfa-behance" => array( "style" => "fab", "code" => "fa-behance" ),
                 "arfa-behance-square" => array( "style" => "fab", "code" => "fa-behance-square" ),
                 "arfa-bitbucket" => array( "style" => "fab", "code" => "fa-bitbucket" ),
                 "arfa-black-tie" => array( "style" => "fab", "code" => "fa-black-tie" ),
                 "arfa-buysellads" => array( "style" => "fab", "code" => "fa-buysellads" ),
                 "arfa-chrome" => array( "style" => "fab", "code" => "fa-chrome" ),
                 "arfa-codepen" => array( "style" => "fab", "code" => "fa-codepen" ),
                 "arfa-codiepie" => array( "style" => "fab", "code" => "fa-codiepie" ),
                 "arfa-connectdevelop" => array( "style" => "fab", "code" => "fa-connectdevelop" ),
                 "arfa-contao" => array( "style" => "fab", "code" => "fa-contao" ),
                 "arfa-css3" => array( "style" => "fab", "code" => "fa-css3" ),
                 "arfa-dashcube" => array( "style" => "fab", "code" => "fa-dashcube" ),
                 "arfa-delicious" => array( "style" => "fab", "code" => "fa-delicious" ),
                 "arfa-deviantart" => array( "style" => "fab", "code" => "fa-deviantart" ),
                 "arfa-digg" => array( "style" => "fab", "code" => "fa-digg" ),
                 "arfa-dribbble" => array( "style" => "fab", "code" => "fa-dribbble" ),
                 "arfa-dropbox" => array( "style" => "fab", "code" => "fa-dropbox" ),
                 "arfa-drupal" => array( "style" => "fab", "code" => "fa-drupal" ),
                 "arfa-edge" => array( "style" => "fab", "code" => "fa-edge" ),
                 "arfa-empire" => array( "style" => "fab", "code" => "fa-empire" ),
                 "arfa-envira" => array( "style" => "fab", "code" => "fa-envira" ),
                 "arfa-expeditedssl" => array( "style" => "fab", "code" => "fa-expeditedssl" ),
                 "arfa-facebook" => array( "style" => "fab", "code" => "fa-facebook-f" ),
                 "arfa-facebook-official" => array( "style" => "fab", "code" => "fa-facebook" ),
                 "arfa-facebook-square" => array( "style" => "fab", "code" => "fa-facebook-square" ),
                 "arfa-firefox" => array( "style" => "fab", "code" => "fa-firefox" ),
                 "arfa-first-order" => array( "style" => "fab", "code" => "fa-first-order" ),
                 "arfa-flickr" => array( "style" => "fab", "code" => "fa-flickr" ),
                 "arfa-font-awesome" => array( "style" => "fab", "code" => "fa-font-awesome" ),
                 "arfa-fonticons" => array( "style" => "fab", "code" => "fa-fonticons" ),
                 "arfa-fort-awesome" => array( "style" => "fab", "code" => "fa-fort-awesome" ),
                 "arfa-forumbee" => array( "style" => "fab", "code" => "fa-forumbee" ),
                 "arfa-foursquare" => array( "style" => "fab", "code" => "fa-foursquare" ),
                 "arfa-get-pocket" => array( "style" => "fab", "code" => "fa-get-pocket" ),
                 "arfa-git" => array( "style" => "fab", "code" => "fa-git" ),
                 "arfa-git-square" => array( "style" => "fab", "code" => "fa-git-square" ),
                 "arfa-github" => array( "style" => "fab", "code" => "fa-github" ),
                 "arfa-github-alt" => array( "style" => "fab", "code" => "fa-github-alt" ),
                 "arfa-github-square" => array( "style" => "fab", "code" => "fa-github-square" ),
                 "arfa-gitlab" => array( "style" => "fab", "code" => "fa-gitlab" ),
                 "arfa-glide" => array( "style" => "fab", "code" => "fa-glide" ),
                 "arfa-glide-g" => array( "style" => "fab", "code" => "fa-glide-g" ),
                 "arfa-google" => array( "style" => "fab", "code" => "fa-google" ),
                 "arfa-google-plus" => array( "style" => "fab", "code" => "fa-google-plus-g" ),
                 "arfa-google-plus-official" => array( "style" => "fab", "code" => "fa-google-plus" ),
                 "arfa-google-plus-square" => array( "style" => "fab", "code" => "fa-google-plus-square" ),
                 "arfa-gratipay" => array( "style" => "fab", "code" => "fa-gratipay" ),
                 "arfa-hacker-news" => array( "style" => "fab", "code" => "fa-hacker-news" ),
                 "arfa-houzz" => array( "style" => "fab", "code" => "fa-houzz" ),
                 "arfa-html5" => array( "style" => "fab", "code" => "fa-html5" ),
                 "arfa-instagram" => array( "style" => "fab", "code" => "fa-instagram" ),
                 "arfa-internet-explorer" => array( "style" => "fab", "code" => "fa-internet-explorer" ),
                 "arfa-ioxhost" => array( "style" => "fab", "code" => "fa-ioxhost" ),
                 "arfa-joomla" => array( "style" => "fab", "code" => "fa-joomla" ),
                 "arfa-jsfiddle" => array( "style" => "fab", "code" => "fa-jsfiddle" ),
                 "arfa-lastfm" => array( "style" => "fab", "code" => "fa-lastfm" ),
                 "arfa-lastfm-square" => array( "style" => "fab", "code" => "fa-lastfm-square" ),
                 "arfa-leanpub" => array( "style" => "fab", "code" => "fa-leanpub" ),
                 "arfa-linkedin" => array( "style" => "fab", "code" => "fa-linkedin-in" ),
                 "arfa-linkedin-square" => array( "style" => "fab", "code" => "fa-linkedin" ),
                 "arfa-linux" => array( "style" => "fab", "code" => "fa-linux" ),
                 "arfa-maxcdn" => array( "style" => "fab", "code" => "fa-maxcdn" ),
                 "arfa-medium" => array( "style" => "fab", "code" => "fa-medium" ),
                 "arfa-mixcloud" => array( "style" => "fab", "code" => "fa-mixcloud" ),
                 "arfa-modx" => array( "style" => "fab", "code" => "fa-modx" ),
                 "arfa-odnoklassniki" => array( "style" => "fab", "code" => "fa-odnoklassniki" ),
                 "arfa-odnoklassniki-square" => array( "style" => "fab", "code" => "fa-odnoklassniki-square" ),
                 "arfa-opencart" => array( "style" => "fab", "code" => "fa-opencart" ),
                 "arfa-openid" => array( "style" => "fab", "code" => "fa-openid" ),
                 "arfa-opera" => array( "style" => "fab", "code" => "fa-opera" ),
                 "arfa-optin-monster" => array( "style" => "fab", "code" => "fa-optin-monster" ),
                 "arfa-pagelines" => array( "style" => "fab", "code" => "fa-pagelines" ),
                 "arfa-pied-piper" => array( "style" => "fab", "code" => "fa-pied-piper-hat" ),
                 "arfa-pied-piper-alt" => array( "style" => "fab", "code" => "fa-pied-piper-alt" ),
                 "arfa-pied-piper-pp" => array( "style" => "fab", "code" => "fa-pied-piper-pp" ),
                 "arfa-pinterest" => array( "style" => "fab", "code" => "fa-pinterest" ),
                 "arfa-pinterest-p" => array( "style" => "fab", "code" => "fa-pinterest-p" ),
                 "arfa-pinterest-square" => array( "style" => "fab", "code" => "fa-pinterest-square" ),
                 "arfa-product-hunt" => array( "style" => "fab", "code" => "fa-product-hunt" ),
                 "arfa-qq" => array( "style" => "fab", "code" => "fa-qq" ),
                 "arfa-rebel" => array( "style" => "fab", "code" => "fa-rebel" ),
                 "arfa-reddit" => array( "style" => "fab", "code" => "fa-reddit" ),
                 "arfa-reddit-alien" => array( "style" => "fab", "code" => "fa-reddit-alien" ),
                 "arfa-reddit-square" => array( "style" => "fab", "code" => "fa-reddit-square" ),
                 "arfa-renren" => array( "style" => "fab", "code" => "fa-renren" ),
                 "arfa-safari" => array( "style" => "fab", "code" => "fa-safari" ),
                 "arfa-scribd" => array( "style" => "fab", "code" => "fa-scribd" ),
                 "arfa-sellsy" => array( "style" => "fab", "code" => "fa-sellsy" ),
                 "arfa-shirtsinbulk" => array( "style" => "fab", "code" => "fa-shirtsinbulk" ),
                 "arfa-simplybuilt" => array( "style" => "fab", "code" => "fa-simplybuilt" ),
                 "arfa-skyatlas" => array( "style" => "fab", "code" => "fa-skyatlas" ),
                 "arfa-skype" => array( "style" => "fab", "code" => "fa-skype" ),
                 "arfa-slack" => array( "style" => "fab", "code" => "fa-slack" ),
                 "arfa-slideshare" => array( "style" => "fab", "code" => "fa-slideshare" ),
                 "arfa-snapchat" => array( "style" => "fab", "code" => "fa-snapchat" ),
                 "arfa-snapchat-ghost" => array( "style" => "fab", "code" => "fa-snapchat-ghost" ),
                 "arfa-snapchat-square" => array( "style" => "fab", "code" => "fa-snapchat-square" ),
                 "arfa-soundcloud" => array( "style" => "fab", "code" => "fa-soundcloud" ),
                 "arfa-spotify" => array( "style" => "fab", "code" => "fa-spotify" ),
                 "arfa-stack-exchange" => array( "style" => "fab", "code" => "fa-stack-exchange" ),
                 "arfa-stack-overflow" => array( "style" => "fab", "code" => "fa-stack-overflow" ),
                 "arfa-steam" => array( "style" => "fab", "code" => "fa-steam-symbol" ),
                 "arfa-steam-square" => array( "style" => "fab", "code" => "fa-steam-square" ),
                 "arfa-stumbleupon" => array( "style" => "fab", "code" => "fa-stumbleupon" ),
                 "arfa-stumbleupon-circle" => array( "style" => "fab", "code" => "fa-stumbleupon-circle" ),
                 "arfa-tencent-weibo" => array( "style" => "fab", "code" => "fa-tencent-weibo" ),
                 "arfa-themeisle" => array( "style" => "fab", "code" => "fa-themeisle" ),
                 "arfa-trello" => array( "style" => "fab", "code" => "fa-trello" ),
                 "arfa-tripadvisor" => array( "style" => "fab", "code" => "fa-tripadvisor" ),
                 "arfa-tumblr" => array( "style" => "fab", "code" => "fa-tumblr" ),
                 "arfa-tumblr-square" => array( "style" => "fab", "code" => "fa-tumblr-square" ),
                 "arfa-twitch" => array( "style" => "fab", "code" => "fa-twitch" ),
                 "arfa-twitter" => array( "style" => "fab", "code" => "fa-twitter" ),
                 "arfa-twitter-square" => array( "style" => "fab", "code" => "fa-twitter-square" ),
                 "arfa-usb" => array( "style" => "fab", "code" => "fa-usb" ),
                 "arfa-viacoin" => array( "style" => "fab", "code" => "fa-viacoin" ),
                 "arfa-viadeo" => array( "style" => "fab", "code" => "fa-viadeo" ),
                 "arfa-viadeo-square" => array( "style" => "fab", "code" => "fa-viadeo-square" ),
                 "arfa-vimeo" => array( "style" => "fab", "code" => "fa-vimeo-v" ),
                 "arfa-vimeo-square" => array( "style" => "fab", "code" => "fa-vimeo-square" ),
                 "arfa-vine" => array( "style" => "fab", "code" => "fa-vine" ),
                 "arfa-vk" => array( "style" => "fab", "code" => "fa-vk" ),
                 "arfa-weibo" => array( "style" => "fab", "code" => "fa-weibo" ),
                 "arfa-weixin" => array( "style" => "fab", "code" => "fa-weixin" ),
                 "arfa-whatsapp" => array( "style" => "fab", "code" => "fa-whatsapp" ),
                 "arfa-wikipedia-w" => array( "style" => "fab", "code" => "fa-wikipedia-w" ),
                 "arfa-windows" => array( "style" => "fab", "code" => "fa-windows" ),
                 "arfa-wordpress" => array( "style" => "fab", "code" => "fa-wordpress" ),
                 "arfa-wpbeginner" => array( "style" => "fab", "code" => "fa-wpbeginner" ),
                 "arfa-wpforms" => array( "style" => "fab", "code" => "fa-wpforms" ),
                 "arfa-xing" => array( "style" => "fab", "code" => "fa-xing" ),
                 "arfa-xing-square" => array( "style" => "fab", "code" => "fa-xing-square" ),
                 "arfa-y-combinator" => array( "style" => "fab", "code" => "fa-y-combinator" ),
                 "arfa-yahoo" => array( "style" => "fab", "code" => "fa-yahoo" ),
                 "arfa-yelp" => array( "style" => "fab", "code" => "fa-yelp" ),
                 "arfa-yoast" => array( "style" => "fab", "code" => "fa-yoast" ),
                 "arfa-youtube" => array( "style" => "fab", "code" => "fa-youtube" ),
                 "arfa-youtube-square" => array( "style" => "fab", "code" => "fa-youtube-square" ),
                 "arfa-h-square" => array( "style" => "fas", "code" => "fa-h-square" ),
                 "arfa-hospital-o" => array( "style" => "far", "code" => "fa-hospital" ),
                 "arfa-medkit" => array( "style" => "fas", "code" => "fa-medkit" ),
                 "arfa-stethoscope" => array( "style" => "fas", "code" => "fa-stethoscope" ),
                 "arfa-user-md" => array( "style" => "fas", "code" => "fa-user-md" ),
                 "arfa-eercast" => array( "style" => "fab", "code" => "fa-sellcast" ),
                 "arfa-youtube-play" => array( "style" => "fab", "code" => "fa-youtube" ),
                 "arfa-bitbucket-square" => array( "style" => "fab", "code" => "fa-bitbucket" ),
                 "arfa-meanpath" => array( "style" => "fab", "code" => "fa-font-awesome"),
                 "arfa-acquisitions-incorporated" => array( "style" => "fab", "code" => "fa-acquisitions-incorporated" ),
                 "arfa-ad" => array( "style" => "fas" , "code" => "fa-arfa-ad" ),
                 "arfa-adobe" => array( "style" => "fab" , "code" => "fa-adobe" ),
                 "arfa-air-freshener" => array( "style" => "fas" , "code" => "fa-air-freshener" ),
                 "arfa-airbnb" => array( "style" => "fab" , "code" => "fa-airbnb" ),
                 "arfa-alipay" => array( "style" => "fab" , "code" => "fa-alipay" ),
                 "arfa-ankh" => array( "style" => "fas" , "code" => "fa-ankh" ),
                 "arfa-apple-alt" => array( "style" => "fas" , "code" => "fa-apple-alt" ),
                 "arfa-artstation" => array( "style" => "fab" , "code" => "fa-artstation" ),
                 "arfa-atlassian" => array( "style" => "fab" , "code" => "fa-atlassian" ),
                 "arfa-atom" => array( "style" => "fas" , "code" => "fa-atom" ),
                 "arfa-baby" => array( "style" => "fas" , "code" => "fa-baby" ),
                 "arfa-baby-carriage" => array( "style" => "fas" , "code" => "fa-baby-carriage" ),
                 "arfa-bacon" => array( "style" => "fas" , "code" => "fa-bacon" ),
                 "arfa-balance-scale-left" => array( "style" => "fas" , "code" => "fa-balance-scale-left" ),
                 "arfa-balance-scale-right" => array( "style" => "fas" , "code" => "fa-balance-scale-right" ),
                 "arfa-battle-net" => array( "style" => "fab" , "code" => "fa-battle-net" ),
                 "arfa-bible" => array( "style" => "fas" , "code" => "fa-bible" ),
                 "arfa-biking" => array( "style" => "fas" , "code" => "fa-biking" ),
                 "arfa-biohazard" => array( "style" => "fas" , "code" => "fa-biohazard" ),
                 "arfa-blender-phone" => array( "style" => "fas" , "code" => "fa-blender-phone" ),
                 "arfa-blog" => array( "style" => "fas" , "code" => "fa-blog" ),
                 "arfa-bone" => array( "style" => "fas" , "code" => "fa-bone" ),
                 "arfa-book-dead" => array( "style" => "fas" , "code" => "fa-book-dead" ),
                 "arfa-book-medical" => array( "style" => "fas" , "code" => "fa-book-medical" ),
                 "arfa-book-reader" => array( "style" => "fas" , "code" => "fa-book-reader" ),
                 "arfa-bootstrap" => array( "style" => "fab" , "code" => "fa-bootstrap" ),
                 "arfa-border-all" => array( "style" => "fas" , "code" => "fa-border-all" ),
                 "arfa-border-none" => array( "style" => "fas" , "code" => "fa-border-none" ),
                 "arfa-border-style" => array( "style" => "fas" , "code" => "fa-border-style" ),
                 "arfa-brain" => array( "style" => "fas" , "code" => "fa-brain" ),
                 "arfa-bread-slice" => array( "style" => "fas" , "code" => "fa-bread-slice" ),
                 "arfa-buffer" => array( "style" => "fab" , "code" => "fa-buffer" ),
                 "arfa-business-time" => array( "style" => "fas" , "code" => "fa-business-time" ),
                 "arfa-buy-n-large" => array( "style" => "fab" , "code" => "fa-buy-n-large" ),
                 "arfa-calendar-day" => array( "style" => "fas" , "code" => "fa-calendar-day" ),
                 "arfa-calendar-week" => array( "style" => "fas" , "code" => "fa-calendar-week" ),
                 "arfa-campground" => array( "style" => "fas" , "code" => "fa-campground" ),
                 "arfa-canadian-maple-leaf" => array( "style" => "fab" , "code" => "fa-canadian-maple-leaf" ),
                 "arfa-candy-cane" => array( "style" => "fas" , "code" => "fa-candy-cane" ),
                 "arfa-car-alt" => array( "style" => "fas" , "code" => "fa-car-alt" ),
                 "arfa-car-battery" => array( "style" => "fas" , "code" => "fa-car-battery" ),
                 "arfa-car-crash" => array( "style" => "fas" , "code" => "fa-car-crash" ),
                 "arfa-car-side" => array( "style" => "fas" , "code" => "fa-car-side" ),
                 "arfa-carrot" => array( "style" => "fas" , "code" => "fa-carrot" ),
                 "arfa-cat" => array( "style" => "fas" , "code" => "fa-cat" ),
                 "arfa-centos" => array( "style" => "fab" , "code" => "fa-centos" ),
                 "arfa-chair" => array( "style" => "fas" , "code" => "fa-chair" ),
                 "arfa-charging-station" => array( "style" => "fas" , "code" => "fa-charging-station" ),
                 "arfa-cheese" => array( "style" => "fas" , "code" => "fa-cheese" ),
                 "arfa-chromecast" => array( "style" => "fab" , "code" => "fa-chromecast" ),
                 "arfa-city" => array( "style" => "fas" , "code" => "fa-city" ),
                 "arfa-clinic-medical" => array( "style" => "fas" , "code" => "fa-clinic-medical" ),
                 "arfa-cloud-meatball" => array( "style" => "fas" , "code" => "fa-cloud-meatball" ),
                 "arfa-cloud-moon" => array( "style" => "fas" , "code" => "fa-cloud-moon" ),
                 "arfa-cloud-moon-rain" => array( "style" => "fas" , "code" => "fa-cloud-moon-rain" ),
                 "arfa-cloud-rain" => array( "style" => "fas" , "code" => "fa-cloud-rain" ),
                 "arfa-cloud-showers-heavy" => array( "style" => "fas" , "code" => "fa-cloud-showers-heavy" ),
                 "arfa-cloud-sun" => array( "style" => "fas" , "code" => "fa-cloud-sun" ),
                 "arfa-cloud-sun-rain" => array( "style" => "fas" , "code" => "fa-cloud-sun-rain" ),
                 "arfa-comment-dollar" => array( "style" => "fas" , "code" => "fa-comment-dollar" ),
                 "arfa-comment-medical" => array( "style" => "fas" , "code" => "fa-comment-medical" ),
                 "arfa-comments-dollar" => array( "style" => "fas" , "code" => "fa-comments-dollar" ),
                 "arfa-compress-arrows-alt" => array( "style" => "fas" , "code" => "fa-compress-arrows-alt" ),
                 "arfa-confluence" => array( "style" => "fab" , "code" => "fa-confluence" ),
                 "arfa-cotton-bureau" => array( "style" => "fab" , "code" => "fa-cotton-bureau" ),
                 "arfa-creative-commons-zero" => array( "style" => "fab" , "code" => "fa-creative-commons-zero" ),
                 "arfa-critical-role" => array( "style" => "fab" , "code" => "fa-critical-role" ),
                 "arfa-cross" => array( "style" => "fas" , "code" => "fa-cross" ),
                 "arfa-crutch" => array( "style" => "fas" , "code" => "fa-crutch" ),
                 "arfa-d-and-d-beyond" => array( "style" => "fab" , "code" => "fa-d-and-d-beyond" ),
                 "arfa-democrat" => array( "style" => "fas" , "code" => "fa-democrat" ),
                 "arfa-dev" => array( "style" => "fab" , "code" => "fa-dev" ),
                 "arfa-dharmachakra" => array( "style" => "fas" , "code" => "fa-dharmachakra" ),
                 "arfa-dhl" => array( "style" => "fab" , "code" => "fa-dhl" ),
                 "arfa-diaspora" => array( "style" => "fab" , "code" => "fa-diaspora" ),
                 "arfa-dice-d20" => array( "style" => "fas" , "code" => "fa-dice-d20" ),
                 "arfa-dice-d6" => array( "style" => "fas" , "code" => "fa-dice-d6" ),
                 "arfa-directions" => array( "style" => "fas" , "code" => "fa-directions" ),
                 "arfa-dog" => array( "style" => "fas" , "code" => "fa-dog" ),
                 "arfa-dragon" => array( "style" => "fas" , "code" => "fa-dragon" ),
                 "arfa-draw-polygon" => array( "style" => "fas" , "code" => "fa-draw-polygon" ),
                 "arfa-drumstick-bite" => array( "style" => "fas" , "code" => "fa-drumstick-bite" ),
                 "arfa-dumpster" => array( "style" => "fas" , "code" => "fa-dumpster" ),
                 "arfa-dumpster-fire" => array( "style" => "fas" , "code" => "fa-dumpster-fire" ),
                 "arfa-dungeon" => array( "style" => "fas" , "code" => "fa-dungeon" ),
                 "arfa-egg" => array( "style" => "fas" , "code" => "fa-egg" ),
                 "arfa-ello" => array( "style" => "fab" , "code" => "fa-ello" ),
                 "arfa-envelope-open-text" => array( "style" => "fas" , "code" => "fa-envelope-open-text" ),
                 "arfa-ethernet" => array( "style" => "fas" , "code" => "fa-ethernet" ),
                 "arfa-evernote" => array( "style" => "fab" , "code" => "fa-evernote" ),
                 "arfa-fan" => array( "style" => "fas" , "code" => "fa-fan" ),
                 "arfa-fantasy-flight-games" => array( "style" => "fab" , "code" => "fa-fantasy-flight-games" ),
                 "arfa-fedex" => array( "style" => "fab" , "code" => "fa-fedex" ),
                 "arfa-fedora" => array( "style" => "fab" , "code" => "fa-fedora" ),
                 "arfa-figma" => array( "style" => "fab" , "code" => "fa-figma" ),
                 "arfa-file-csv" => array( "style" => "fas" , "code" => "fa-file-csv" ),
                 "arfa-fire-alt" => array( "style" => "fas" , "code" => "fa-fire-alt" ),
                 "arfa-fist-raised" => array( "style" => "fas" , "code" => "fa-fist-raised" ),
                 "arfa-flag-usa" => array( "style" => "fas" , "code" => "fa-flag-usa" ),
                 "arfa-folder-minus" => array( "style" => "fas" , "code" => "fa-folder-minus" ),
                 "arfa-folder-plus" => array( "style" => "fas" , "code" => "fa-folder-plus" ),
                 "arfa-funnel-dollar" => array( "style" => "fas" , "code" => "fa-funnel-dollar" ),
                 "arfa-ghost" => array( "style" => "fas" , "code" => "fa-ghost" ),
                 "arfa-gifts" => array( "style" => "fas" , "code" => "fa-gifts" ),
                 "arfa-git-alt" => array( "style" => "fab" , "code" => "fa-git-alt" ),
                 "arfa-glass-cheers" => array( "style" => "fas" , "code" => "fa-glass-cheers" ),
                 "arfa-glass-whiskey" => array( "style" => "fas" , "code" => "fa-glass-whiskey" ),
                 "arfa-globe-europe" => array( "style" => "fas" , "code" => "fa-globe-europe" ),
                 "arfa-gopuram" => array( "style" => "fas" , "code" => "fa-gopuram" ),
                 "arfa-grip-lines" => array( "style" => "fas" , "code" => "fa-grip-lines" ),
                 "arfa-grip-lines-vertical" => array( "style" => "fas" , "code" => "fa-grip-lines-vertical" ),
                 "arfa-guitar" => array( "style" => "fas" , "code" => "fa-guitar" ),
                 "arfa-hackerrank" => array( "style" => "fab" , "code" => "fa-hackerrank" ),
                 "arfa-hamburger" => array( "style" => "fas" , "code" => "fa-hamburger" ),
                 "arfa-hammer" => array( "style" => "fas" , "code" => "fa-hammer" ),
                 "arfa-hamsa" => array( "style" => "fas" , "code" => "fa-hamsa" ),
                 "arfa-hand-middle-finger" => array( "style" => "fas" , "code" => "fa-hand-middle-finger" ),
                 "arfa-hanukiah" => array( "style" => "fas" , "code" => "fa-hanukiah" ),
                 "arfa-hard-hat" => array( "style" => "fas" , "code" => "fa-hard-hat" ),
                 "arfa-hat-cowboy" => array( "style" => "fas" , "code" => "fa-hat-cowboy" ),
                 "arfa-hat-cowboy-side" => array( "style" => "fas" , "code" => "fa-hat-cowboy-side" ),
                 "arfa-hat-wizard" => array( "style" => "fas" , "code" => "fa-hat-wizard" ),
                 "arfa-heart-broken" => array( "style" => "fas" , "code" => "fa-heart-broken" ),
                 "arfa-hiking" => array( "style" => "fas" , "code" => "fa-hiking" ),
                 "arfa-hippo" => array( "style" => "fas" , "code" => "fa-hippo" ),
                 "arfa-holly-berry" => array( "style" => "fas" , "code" => "fa-holly-berry" ),
                 "arfa-horse" => array( "style" => "fas" , "code" => "fa-horse" ),
                 "arfa-horse-head" => array( "style" => "fas" , "code" => "fa-horse-head" ),
                 "arfa-hotdog" => array( "style" => "fas" , "code" => "fa-hotdog" ),
                 "arfa-house-damage" => array( "style" => "fas" , "code" => "fa-house-damage" ),
                 "arfa-hryvnia" => array( "style" => "fas" , "code" => "fa-hryvnia" ),
                 "arfa-ice-cream" => array( "style" => "fas" , "code" => "fa-ice-cream" ),
                 "arfa-icicles" => array( "style" => "fas" , "code" => "fa-icicles" ),
                 "arfa-icons" => array( "style" => "fas" , "code" => "fa-icons" ),
                 "arfa-igloo" => array( "style" => "fas" , "code" => "fa-igloo" ),
                 "arfa-intercom" => array( "style" => "fab" , "code" => "fa-intercom" ),
                 "arfa-invision" => array( "style" => "fab" , "code" => "fa-invision" ),
                 "arfa-itch-io" => array( "style" => "fab" , "code" => "fa-itch-io" ),
                 "arfa-jedi" => array( "style" => "fas" , "code" => "fa-jedi" ),
                 "arfa-jira" => array( "style" => "fab" , "code" => "fa-jira" ),
                 "arfa-journal-whills" => array( "style" => "fas" , "code" => "fa-journal-whills" ),
                 "arfa-kaaba" => array( "style" => "fas" , "code" => "fa-kaaba" ),
                 "arfa-kaggle" => array( "style" => "fab" , "code" => "fa-kaggle" ),
                 "arfa-khanda" => array( "style" => "fas" , "code" => "fa-khanda" ),
                 "arfa-landmark" => array( "style" => "fas" , "code" => "fa-landmark" ),
                 "arfa-laptop-code" => array( "style" => "fas" , "code" => "fa-laptop-code" ),
                 "arfa-laptop-medical" => array( "style" => "fas" , "code" => "fa-laptop-medical" ),
                 "arfa-layer-group" => array( "style" => "fas" , "code" => "fa-layer-group" ),
                 "arfa-mail-bulk" => array( "style" => "fas" , "code" => "fa-mail-bulk" ),
                 "arfa-markdown" => array( "style" => "fab" , "code" => "fa-markdown" ),
                 "arfa-marker" => array( "style" => "fas" , "code" => "fa-marker" ),
                 "arfa-mask" => array( "style" => "fas" , "code" => "fa-mask" ),
                 "arfa-mdb" => array( "style" => "fab" , "code" => "fa-mdb" ),
                 "arfa-medal" => array( "style" => "fas" , "code" => "fa-medal" ),
                 "arfa-megaport" => array( "style" => "fab" , "code" => "fa-megaport" ),
                 "arfa-meh-blank" => array( "style" => "fas" , "code" => "fa-meh-blank" ),
                 "arfa-meh-rolling-eyes" => array( "style" => "fas" , "code" => "fa-meh-rolling-eyes" ),
                 "arfa-mendeley" => array( "style" => "fab" , "code" => "fa-mendeley" ),
                 "arfa-menorah" => array( "style" => "fas" , "code" => "fa-menorah" ),
                 "arfa-meteor" => array( "style" => "fas" , "code" => "fa-meteor" ),
                 "arfa-microscope" => array( "style" => "fas" , "code" => "fa-microscope" ),
                 "arfa-mitten" => array( "style" => "fas" , "code" => "fa-mitten" ),
                 "arfa-mosque" => array( "style" => "fas" , "code" => "fa-mosque" ),
                 "arfa-mountain" => array( "style" => "fas" , "code" => "fa-mountain" ),
                 "arfa-mouse" => array( "style" => "fas" , "code" => "fa-mouse" ),
                 "arfa-mug-hot" => array( "style" => "fas" , "code" => "fa-mug-hot" ),
                 "arfa-neos" => array( "style" => "fab" , "code" => "fa-neos" ),
                 "arfa-network-wired" => array( "style" => "fas" , "code" => "fa-network-wired" ),
                 "arfa-oil-can" => array( "style" => "fas" , "code" => "fa-oil-can" ),
                 "arfa-om" => array( "style" => "fas" , "code" => "fa-om" ),
                 "arfa-orcid" => array( "style" => "fab" , "code" => "fa-orcid" ),
                 "arfa-otter" => array( "style" => "fas" , "code" => "fa-otter" ),
                 "arfa-pager" => array( "style" => "fas" , "code" => "fa-pager" ),
                 "arfa-peace" => array( "style" => "fas" , "code" => "fa-peace" ),
                 "arfa-penny-arcade" => array( "style" => "fab" , "code" => "fa-penny-arcade" ),
                 "arfa-pepper-hot" => array( "style" => "fas" , "code" => "fa-pepper-hot" ),
                 "arfa-person-booth" => array( "style" => "fas" , "code" => "fa-person-booth" ),
                 "arfa-phone-alt" => array( "style" => "fas" , "code" => "fa-phone-alt" ),
                 "arfa-phone-square-alt" => array( "style" => "fas" , "code" => "fa-phone-square-alt" ),
                 "arfa-photo-video" => array( "style" => "fas" , "code" => "fa-photo-video" ),
                 "arfa-pizza-slice" => array( "style" => "fas" , "code" => "fa-pizza-slice" ),
                 "arfa-place-of-worship" => array( "style" => "fas" , "code" => "fa-place-of-worship" ),
                 "arfa-poll" => array( "style" => "fas" , "code" => "fa-poll" ),
                 "arfa-poll-h" => array( "style" => "fas" , "code" => "fa-poll-h" ),
                 "arfa-poo-storm" => array( "style" => "fas" , "code" => "fa-poo-storm" ),
                 "arfa-poop" => array( "style" => "fas" , "code" => "fa-poop" ),
                 "arfa-pray" => array( "style" => "fas" , "code" => "fa-pray" ),
                 "arfa-praying-hands" => array( "style" => "fas" , "code" => "fa-praying-hands" ),
                 "arfa-quran" => array( "style" => "fas" , "code" => "fa-quran" ),
                 "arfa-radiation" => array( "style" => "fas" , "code" => "fa-radiation" ),
                 "arfa-radiation-alt" => array( "style" => "fas" , "code" => "fa-radiation-alt" ),
                 "arfa-rainbow" => array( "style" => "fas" , "code" => "fa-rainbow" ),
                 "arfa-raspberry-pi" => array( "style" => "fab" , "code" => "fa-raspberry-pi" ),
                 "arfa-reacteurope" => array( "style" => "fab" , "code" => "fa-reacteurope" ),
                 "arfa-record-vinyl" => array( "style" => "fas" , "code" => "fa-record-vinyl" ),
                 "arfa-redhat" => array( "style" => "fab" , "code" => "fa-redhat" ),
                 "arfa-remove-format" => array( "style" => "fas" , "code" => "fa-remove-format" ),
                 "arfa-republican" => array( "style" => "fas" , "code" => "fa-republican" ),
                 "arfa-restroom" => array( "style" => "fas" , "code" => "fa-restroom" ),
                 "arfa-rev" => array( "style" => "fab" , "code" => "fa-rev" ),
                 "arfa-ring" => array( "style" => "fas" , "code" => "fa-ring" ),
                 "arfa-route" => array( "style" => "fas" , "code" => "fa-route" ),
                 "arfa-running" => array( "style" => "fas" , "code" => "fa-running" ),
                 "arfa-salesforce" => array( "style" => "fab" , "code" => "fa-salesforce" ),
                 "arfa-satellite" => array( "style" => "fas" , "code" => "fa-satellite" ),
                 "arfa-satellite-dish" => array( "style" => "fas" , "code" => "fa-satellite-dish" ),
                 "arfa-scroll" => array( "style" => "fas" , "code" => "fa-scroll" ),
                 "arfa-sd-card" => array( "style" => "fas" , "code" => "fa-sd-card" ),
                 "arfa-search-dollar" => array( "style" => "fas" , "code" => "fa-search-dollar" ),
                 "arfa-search-location" => array( "style" => "fas" , "code" => "fa-search-location" ),
                 "arfa-shapes" => array( "style" => "fas" , "code" => "fa-shapes" ),
                 "arfa-sim-card" => array( "style" => "fas" , "code" => "fa-sim-card" ),
                 "arfa-skating" => array( "style" => "fas" , "code" => "fa-skating" ),
                 "arfa-sketch" => array( "style" => "fab" , "code" => "fa-sketch" ),
                 "arfa-skiing" => array( "style" => "fas" , "code" => "fa-skiing" ),
                 "arfa-skiing-nordic" => array( "style" => "fas" , "code" => "fa-skiing-nordic" ),
                 "arfa-skull-crossbones" => array( "style" => "fas" , "code" => "fa-skull-crossbones" ),
                 "arfa-slash" => array( "style" => "fas" , "code" => "fa-slash" ),
                 "arfa-sleigh" => array( "style" => "fas" , "code" => "fa-sleigh" ),
                 "arfa-smog" => array( "style" => "fas" , "code" => "fa-smog" ),
                 "arfa-sms" => array( "style" => "fas" , "code" => "fa-sms" ),
                 "arfa-snowboarding" => array( "style" => "fas" , "code" => "fa-snowboarding" ),
                 "arfa-snowman" => array( "style" => "fas" , "code" => "fa-snowman" ),
                 "arfa-snowplow" => array( "style" => "fas" , "code" => "fa-snowplow" ),
                 "arfa-socks" => array( "style" => "fas" , "code" => "fa-socks" ),
                 "arfa-sort-alpha-down-alt" => array( "style" => "fas" , "code" => "fa-sort-alpha-down-alt" ),
                 "arfa-sort-alpha-up-alt" => array( "style" => "fas" , "code" => "fa-sort-alpha-up-alt" ),
                 "arfa-sort-amount-down-alt" => array( "style" => "fas" , "code" => "fa-sort-amount-down-alt" ),
                 "arfa-sort-amount-up-alt" => array( "style" => "fas" , "code" => "fa-sort-amount-up-alt" ),
                 "arfa-sort-numeric-down-alt" => array( "style" => "fas" , "code" => "fa-sort-numeric-down-alt" ),
                 "arfa-sort-numeric-up-alt" => array( "style" => "fas" , "code" => "fa-sort-numeric-up-alt" ),
                 "arfa-sourcetree" => array( "style" => "fab" , "code" => "fa-sourcetree" ),
                 "arfa-speaker-deck" => array( "style" => "fab" , "code" => "fa-speaker-deck" ),
                 "arfa-spell-check" => array( "style" => "fas" , "code" => "fa-spell-check" ),
                 "arfa-spider" => array( "style" => "fas" , "code" => "fa-spider" ),
                 "arfa-square-root-alt" => array( "style" => "fas" , "code" => "fa-square-root-alt" ),
                 "arfa-stackpath" => array( "style" => "fab" , "code" => "fa-stackpath" ),
                 "arfa-star-and-crescent" => array( "style" => "fas" , "code" => "fa-star-and-crescent" ),
                 "arfa-star-of-david" => array( "style" => "fas" , "code" => "fa-star-of-david" ),
                 "arfa-star-of-life" => array( "style" => "fas" , "code" => "fa-star-of-life" ),
                 "arfa-suse" => array( "style" => "fab" , "code" => "fa-suse" ),
                 "arfa-swift" => array( "style" => "fab" , "code" => "fa-swift" ),
                 "arfa-symfony" => array( "style" => "fab" , "code" => "fa-symfony" ),
                 "arfa-synagogue" => array( "style" => "fas" , "code" => "fa-synagogue" ),
                 "arfa-teeth" => array( "style" => "fas" , "code" => "fa-teeth" ),
                 "arfa-teeth-open" => array( "style" => "fas" , "code" => "fa-teeth-open" ),
                 "arfa-temperature-high" => array( "style" => "fas" , "code" => "fa-temperature-high" ),
                 "arfa-temperature-low" => array( "style" => "fas" , "code" => "fa-temperature-low" ),
                 "arfa-tenge" => array( "style" => "fas" , "code" => "fa-tenge" ),
                 "arfa-the-red-yeti" => array( "style" => "fab" , "code" => "fa-the-red-yeti" ),
                 "arfa-theater-masks" => array( "style" => "fas" , "code" => "fa-theater-masks" ),
                 "arfa-think-peaks" => array( "style" => "fab" , "code" => "fa-think-peaks" ),
                 "arfa-toilet" => array( "style" => "fas" , "code" => "fa-toilet" ),
                 "arfa-toilet-paper" => array( "style" => "fas" , "code" => "fa-toilet-paper" ),
                 "arfa-tools" => array( "style" => "fas" , "code" => "fa-tools" ),
                 "arfa-torah" => array( "style" => "fas" , "code" => "fa-torah" ),
                 "arfa-torii-gate" => array( "style" => "fas" , "code" => "fa-torii-gate" ),
                 "arfa-tractor" => array( "style" => "fas" , "code" => "fa-tractor" ),
                 "arfa-traffic-light" => array( "style" => "fas" , "code" => "fa-traffic-light" ),
                 "arfa-tram" => array( "style" => "fas" , "code" => "fa-tram" ),
                 "arfa-trash-restore" => array( "style" => "fas" , "code" => "fa-trash-restore" ),
                 "arfa-trash-restore-alt" => array( "style" => "fas" , "code" => "fa-trash-restore-alt" ),
                 "arfa-truck-monster" => array( "style" => "fas" , "code" => "fa-truck-monster" ),
                 "arfa-truck-pickup" => array( "style" => "fas" , "code" => "fa-truck-pickup" ),
                 "arfa-ubuntu" => array( "style" => "fab" , "code" => "fa-ubuntu" ),
                 "arfa-umbraco" => array( "style" => "fab" , "code" => "fa-umbraco" ),
                 "arfa-ups" => array( "style" => "fab" , "code" => "fa-ups" ),
                 "arfa-user-injured" => array( "style" => "fas" , "code" => "fa-user-injured" ),
                 "arfa-user-nurse" => array( "style" => "fas" , "code" => "fa-user-nurse" ),
                 "arfa-usps" => array( "style" => "fab" , "code" => "fa-usps" ),
                 "arfa-vihara" => array( "style" => "fas" , "code" => "fa-vihara" ),
                 "arfa-voicemail" => array( "style" => "fas" , "code" => "fa-voicemail" ),
                 "arfa-volume-mute" => array( "style" => "fas" , "code" => "fa-volume-mute" ),
                 "arfa-vote-yea" => array( "style" => "fas" , "code" => "fa-vote-yea" ),
                 "arfa-vr-cardboard" => array( "style" => "fas" , "code" => "fa-vr-cardboard" ),
                 "arfa-water" => array( "style" => "fas" , "code" => "fa-water" ),
                 "arfa-wave-square" => array( "style" => "fas" , "code" => "fa-wave-square" ),
                 "arfa-waze" => array( "style" => "fab" , "code" => "fa-waze" ),
                 "arfa-wind" => array( "style" => "fas" , "code" => "fa-wind" ),
                 "arfa-wine-bottle" => array( "style" => "fas" , "code" => "fa-wine-bottle" ),
                 "arfa-wizards-of-the-coast" => array( "style" => "fab" , "code" => "fa-wizards-of-the-coast" ),
                 "arfa-wpressr" => array( "style" => "fab" , "code" => "fa-wpressr" ),
                 "arfa-yammer" => array( "style" => "fab" , "code" => "fa-yammer" ),
                 "arfa-yarn" => array( "style" => "fab" , "code" => "fa-yarn" ),
                 "arfa-yin-yang" => array( "style" => "fas" , "code" => "fa-yin-yang" ),
                 "arfa-zhihu" => array( "style" => "fab" , "code" => "fa-zhihu" ),
                 "arfa-bahai" => array( "style" => "fas" , "code" => "fa-bahai" ),
                 "arfa-caravan" => array( "style" => "fas" , "code" => "fa-caravan" ),
                 "arfa-compress-alt" => array( "style" => "fas" , "code" => "fa-compress-alt" ),
                 "arfa-expand-alt" => array( "style" => "fas" , "code" => "fa-expand-alt" ),
                 "arfa-firefox-browser" => array( "style" => "fab" , "code" => "fa-firefox-browser" ),
                 "arfa-ideal" => array( "style" => "fab" , "code" => "fa-ideal" ),
                 "arfa-microblog" => array( "style" => "fab" , "code" => "fa-microblog" ),
                 "arfa-pied-piper-square" => array( "style" => "fab" , "code" => "fa-pied-piper-square" ),
                 "arfa-trailer" => array( "style" => "fas" , "code" => "fa-trailer" ),
            );
        return $font_awesome_icon;

    }

    $array_val =arforms_font_awesome_font_array();